### ISSUE TITLE
Switch to FXML

### ISSUE THREAD

**Issue by ArchdukeTim** [WPISoftEng/CS3733-Starter-Code#4]
Wong is only using javafx for one more term. It isn't worth it to try to switch everything over to not fxml

**Comment by gusteran** [comment]
However, a good example of generating useful UI without fxml could be useful as many people come to think that JavaFX requires fxmls

**Comment by ArchdukeTim** [comment]
If there was more than one more term of JavaFX, I would, but after experimenting I've found ways of making fxmls actually quite easy to work with, and in some cases even easier than having a scene.

**Comment by GregoryConrad** [comment]
Out of curiosity, what does Wong plan to switch to instead of JavaFX?

**Comment by ArchdukeTim** [comment]
He's thinking angular for future years. But I'm gonna try to convince him to not due to OOAD (4233) being in Java
